def lesson(i, title, summary, idea, method, example, checklist):
    body = f"""{title.upper()}

KHÁI NIỆM
{idea}

CÁCH ÁP DỤNG
{method}

VÍ DỤ THỰC TẾ
{example}

CHECKLIST
{checklist}

BÀI HỌC CHÍNH
Hãy biến khái niệm thành một hành động nhỏ có thể kiểm tra được trong công việc thực tế."""
    return {"id": i, "title": title, "summary": summary, "content": body}

CHAPTERS = [
{
"title":"1. Tư duy đúng trước khi hành động",
"subtitle":"Nền tảng để nhìn đúng vấn đề trước khi chọn giải pháp.",
"lessons":[
lesson("1.1","Tư duy là gì?","Hiểu tư duy như một quá trình biến thông tin thành quyết định.",
"Tư duy là quá trình tiếp nhận thông tin, đặt câu hỏi, kết nối dữ kiện, hình thành nhận định và lựa chọn hành động. Chất lượng hành động phụ thuộc mạnh vào chất lượng suy nghĩ trước đó.",
"Trước một vấn đề, hãy tách ba lớp: điều đã biết, điều đang giả định và điều cần kiểm tra. Không hành động chỉ vì cảm giác “có vẻ đúng”.",
"Một công đoạn tăng lỗi. Thay vì quy trách nhiệm ngay cho operator, nhóm kiểm tra dữ liệu theo máy, vật liệu, model, ca và phương pháp trước khi kết luận.",
"☐ Dữ kiện đã xác nhận?\n☐ Giả định nào đang tồn tại?\n☐ Cần thêm bằng chứng gì?"),
lesson("1.2","Fact – Opinion – Assumption","Phân biệt dữ kiện, ý kiến và giả định.",
"Fact là điều có thể kiểm chứng. Opinion là cách diễn giải. Assumption là điều tạm cho là đúng khi chưa đủ bằng chứng.",
"Khi họp hoặc viết báo cáo, gắn nhãn rõ thông tin thuộc loại nào. Chỉ dùng fact làm nền cho quyết định; opinion và assumption phải được kiểm chứng.",
"Fact: NG 2,8%. Opinion: máy không ổn định. Assumption: lỗi tăng do vật liệu nhà cung cấp mới.",
"☐ Có số liệu gốc?\n☐ Có đang biến ý kiến thành sự thật?\n☐ Giả định nào cần test?"),
lesson("1.3","Critical Thinking","Kiểm tra chất lượng của thông tin và kết luận.",
"Tư duy phản biện không phải phản đối mọi thứ mà là kiểm tra độ tin cậy của một lập luận trước khi chấp nhận.",
"Hỏi: nguồn dữ liệu ở đâu, bằng chứng nào hỗ trợ, có cách giải thích khác không, điều gì có thể làm kết luận sai và rủi ro nếu quyết định sai là gì.",
"Một báo cáo nói action đã cải tiến. Ta kiểm tra baseline, cỡ mẫu, điều kiện trước/sau và thời gian theo dõi thay vì chỉ đọc kết luận.",
"☐ Nguồn dữ liệu rõ?\n☐ Có đối chứng?\n☐ Có giả thuyết thay thế?"),
lesson("1.4","First Principles Thinking","Tách vấn đề về những yếu tố cơ bản nhất.",
"First Principles là cách không bắt đầu từ “người khác đang làm thế nào” mà quay về bản chất: điều gì thực sự đúng và điều gì chỉ là thói quen.",
"Liệt kê các giả định hiện tại, bóc tách chúng, giữ lại các ràng buộc thật sự rồi xây giải pháp từ nền tảng đó.",
"Một công đoạn luôn cần hai người vì lịch sử vẫn làm vậy. Phân tích thao tác cho thấy chỉ một bước cần hai người; phần còn lại có thể thiết kế lại.",
"☐ Giả định nào chỉ là thói quen?\n☐ Ràng buộc nào là thật?\n☐ Có thể thiết kế lại từ gốc?"),
]},

{
"title":"2. Tư duy logic và tư duy hệ thống",
"subtitle":"Xây dựng chuỗi lập luận rõ ràng và nhìn vấn đề trong toàn hệ thống.",
"lessons":[
lesson("2.1","Logical Thinking","Sắp xếp thông tin theo chuỗi nguyên nhân – kết quả.",
"Tư duy logic biến một vấn đề phức tạp thành chuỗi lập luận mà người khác có thể kiểm tra.",
"Dùng cấu trúc: hiện tượng → dữ kiện → giả thuyết → kiểm chứng → kết luận → hành động.",
"Yield giảm. Dữ liệu chỉ ra lỗi tập trung trên một máy. Test xác nhận độ lệch áp lực. Action tập trung vào regulator thay vì toàn bộ line.",
"☐ Chuỗi nguyên nhân có liền mạch?\n☐ Kết luận có dựa trên dữ liệu?\n☐ Action có gắn với nguyên nhân?"),
lesson("2.2","System Thinking","Nhìn lỗi như một phần của hệ thống.",
"Một lỗi hiếm khi tồn tại độc lập. Nó có thể liên quan con người, thiết bị, tiêu chuẩn, thông tin, vật liệu và cơ chế quản lý.",
"Không chỉ hỏi “ai làm sai?” mà hỏi “hệ thống nào cho phép lỗi xảy ra hoặc lọt qua?”.",
"Operator nhập sai thông số. Nếu máy cho phép nhập ngoài spec mà không cảnh báo thì root cause không chỉ nằm ở operator.",
"☐ Có xem xét 4M/5M1E?\n☐ Có điểm kiểm soát hệ thống?\n☐ Action có ngăn tái diễn?"),
lesson("2.3","MECE","Chia vấn đề đầy đủ nhưng không chồng chéo.",
"MECE giúp phân loại một vấn đề thành các nhóm Mutually Exclusive, Collectively Exhaustive: không trùng nhau và đủ bao phủ.",
"Trước khi phân tích, xác định một tiêu chí phân nhóm rõ ràng như theo máy, model, ca, lỗi hoặc công đoạn.",
"Khi phân tích NG, không nên trộn “machine 1”, “night shift” và “model A” trong cùng một danh sách nguyên nhân vì chúng thuộc các trục khác nhau.",
"☐ Nhóm có bị chồng chéo?\n☐ Có phần nào bị bỏ sót?\n☐ Tiêu chí phân nhóm nhất quán?"),
lesson("2.4","Cause – Effect Mapping","Xây bản đồ nguyên nhân và tác động.",
"Bản đồ cause-effect giúp thấy nhiều nguyên nhân có thể cùng dẫn đến một kết quả và một nguyên nhân có thể gây nhiều hệ quả.",
"Viết outcome ở bên phải, liệt kê các driver chính ở bên trái, sau đó nối bằng quan hệ có bằng chứng.",
"Scrap tăng có thể liên quan material variation, machine setup và detection escape. Mỗi nhánh cần dữ liệu xác nhận riêng.",
"☐ Outcome được định nghĩa rõ?\n☐ Driver có bằng chứng?\n☐ Có phân biệt nguyên nhân và triệu chứng?"),
]},

{
"title":"3. Phương pháp giải quyết vấn đề",
"subtitle":"Từ hiện tượng đến nguyên nhân gốc và hành động có hiệu lực.",
"lessons":[
lesson("3.1","5 Why","Đi từ hiện tượng đến nguyên nhân gốc.",
"5 Why là kỹ thuật hỏi “Tại sao?” liên tiếp để đi từ symptom đến nguyên nhân có thể kiểm soát. Không nhất thiết đúng 5 lần.",
"Mỗi câu trả lời phải nối logic với câu trước và có bằng chứng. Dừng khi tìm được nguyên nhân có thể tác động ở cấp hệ thống.",
"Machine stop → sensor lệch → bracket lỏng → screw không kiểm soát torque → WI không quy định torque.",
"☐ Mỗi Why có bằng chứng?\n☐ Không dừng ở “operator mistake”?\n☐ Action xử lý root cause?"),
lesson("3.2","Fishbone","Mở rộng góc nhìn nguyên nhân theo nhóm.",
"Fishbone hay Ishikawa giúp brainstorm nguyên nhân theo các nhóm như Man, Machine, Material, Method, Measurement, Environment.",
"Chỉ dùng sơ đồ để mở rộng khả năng; sau đó từng nguyên nhân phải được xác nhận bằng dữ liệu.",
"Defect tăng có thể có nhánh machine pressure, material thickness, method setting, measurement bias và operator handling.",
"☐ Đủ nhóm nguyên nhân?\n☐ Có bằng chứng xác nhận?\n☐ Đã loại bỏ nguyên nhân không phù hợp?"),
lesson("3.3","Pareto","Tập trung vào số ít nguyên nhân tạo phần lớn tác động.",
"Pareto giúp xếp hạng các nhóm lỗi theo tần suất hoặc mức ảnh hưởng để ưu tiên nguồn lực.",
"Chuẩn hóa cách phân loại trước khi vẽ. Tập trung top defect nhưng không bỏ qua lỗi nhỏ có rủi ro an toàn hoặc khách hàng cao.",
"Ba loại defect chiếm 78% tổng NG; đội dự án ưu tiên hai lỗi đầu có khả năng cải thiện nhanh nhất.",
"☐ Dữ liệu cùng kỳ?\n☐ Phân loại nhất quán?\n☐ Có xem xét severity ngoài frequency?"),
lesson("3.4","PDCA","Chu trình cải tiến liên tục.",
"PDCA gồm Plan, Do, Check, Act. Giá trị nằm ở việc biến cải tiến thành vòng học tập, không phải bốn ô trong báo cáo.",
"Lập kế hoạch có giả thuyết; chạy thử có kiểm soát; kiểm tra bằng dữ liệu; sau đó chuẩn hóa hoặc điều chỉnh.",
"Thay đổi parameter trên một máy thử nghiệm, theo dõi ba ngày, so với baseline rồi mới rollout toàn line.",
"☐ Có target?\n☐ Có baseline?\n☐ Có tiêu chí thành công?\n☐ Có chuẩn hóa sau khi hiệu quả?"),
]},

{
"title":"4. Ra quyết định dựa trên dữ liệu",
"subtitle":"Đánh giá dữ liệu, rủi ro và phương án trước khi quyết định.",
"lessons":[
lesson("4.1","Data before Decision","Ưu tiên bằng chứng trước cảm tính.",
"Quyết định tốt không đòi hỏi dữ liệu hoàn hảo, nhưng cần biết dữ liệu nào đủ để giảm rủi ro chính.",
"Xác định câu hỏi quyết định trước, rồi thu đúng dữ liệu cần thiết thay vì gom mọi thứ.",
"Chọn supplier không chỉ nhìn giá; cần chất lượng, delivery, capacity, risk và tổng chi phí.",
"☐ Câu hỏi quyết định rõ?\n☐ Dữ liệu liên quan trực tiếp?\n☐ Có thiếu biến quan trọng?"),
lesson("4.2","Baseline & Target","Đặt điểm xuất phát và mục tiêu rõ.",
"Baseline cho biết trạng thái hiện tại; target xác định mức cần đạt. Không có baseline thì khó chứng minh cải tiến.",
"Chốt thời kỳ baseline đủ đại diện, xác định metric và điều kiện đo, rồi đặt target có thời hạn.",
"FAI defect baseline 1,4%; target ≤0,7% trong 4 tuần với cùng model mix.",
"☐ Baseline đại diện?\n☐ Target có deadline?\n☐ Điều kiện so sánh tương đương?"),
lesson("4.3","Decision Matrix","So sánh phương án theo tiêu chí có trọng số.",
"Decision Matrix giúp tránh việc một tiêu chí nổi bật lấn át toàn bộ quyết định.",
"Liệt kê tiêu chí, gán trọng số, chấm từng phương án theo cùng thang điểm, sau đó xem sensitivity.",
"Supplier A giá thấp hơn nhưng risk delivery cao; supplier B ổn định hơn. Ma trận giúp thấy trade-off minh bạch.",
"☐ Tiêu chí đầy đủ?\n☐ Trọng số hợp lý?\n☐ Có kiểm tra sensitivity?"),
lesson("4.4","Risk-based Decision","Ra quyết định theo xác suất và mức hậu quả.",
"Rủi ro là sự kết hợp giữa khả năng xảy ra và mức tác động. Một việc ít xảy ra nhưng hậu quả lớn vẫn cần ưu tiên.",
"Đánh giá probability, severity và detectability khi phù hợp; xác định ngưỡng chấp nhận trước khi quyết định.",
"Một thay đổi process có gain nhỏ nhưng có nguy cơ customer escape nghiêm trọng; quyết định phải cân risk trước gain.",
"☐ Worst case là gì?\n☐ Có control giảm risk?\n☐ Ai chấp nhận residual risk?"),
]},

{
"title":"5. Quản lý công việc và thời gian",
"subtitle":"Ưu tiên đúng, quản lý tải công việc và duy trì nhịp thực thi.",
"lessons":[
lesson("5.1","Eisenhower Matrix","Phân biệt việc quan trọng và việc khẩn cấp.",
"Ma trận Eisenhower chia công việc thành bốn nhóm theo mức khẩn cấp và quan trọng.",
"Ưu tiên làm ngay việc quan trọng-khẩn; lên lịch việc quan trọng-chưa khẩn; ủy quyền khi phù hợp; loại bỏ việc ít giá trị.",
"Chuẩn bị audit tuần sau là quan trọng nhưng chưa khẩn; xử lý line stop hiện tại là vừa quan trọng vừa khẩn.",
"☐ Việc nào tạo tác động lớn?\n☐ Việc nào có thể lên lịch?\n☐ Việc nào nên ủy quyền?"),
lesson("5.2","Time Blocking","Bảo vệ thời gian cho việc cần tập trung.",
"Time blocking là đặt trước khung giờ cho nhóm công việc thay vì phản ứng liên tục theo tin nhắn.",
"Chặn 60–90 phút cho deep work, gom họp và xử lý email vào khung riêng.",
"Engineer dành 9:00–10:30 phân tích DOE, thay vì liên tục ngắt quãng bởi email không khẩn.",
"☐ Có khung deep work?\n☐ Có buffer cho việc phát sinh?\n☐ Calendar phản ánh ưu tiên?"),
lesson("5.3","WIP Limit","Giới hạn số việc đang làm đồng thời.",
"WIP quá cao tạo chuyển đổi ngữ cảnh, kéo dài lead time và khiến nhiều việc đều dở dang.",
"Đặt giới hạn số nhiệm vụ active cho cá nhân hoặc team. Hoàn thành trước khi kéo thêm việc mới.",
"Một engineer chỉ giữ tối đa 3 action active; việc mới phải thay thế hoặc chờ trong backlog.",
"☐ Có quá nhiều việc active?\n☐ Có định nghĩa Done?\n☐ Có backlog rõ ràng?"),
lesson("5.4","Weekly Review","Duy trì nhịp xem lại và điều chỉnh.",
"Weekly Review giúp đóng vòng giữa kế hoạch và thực tế.",
"Mỗi tuần xem mục tiêu, việc đã hoàn thành, việc trễ, blocker, bài học và ưu tiên tuần tới.",
"Thứ Sáu 30 phút review action list giúp phát hiện sớm các nhiệm vụ đã trễ owner hoặc deadline.",
"☐ Top 3 tuần tới?\n☐ Action trễ vì sao?\n☐ Có việc nào nên dừng?"),
]},

{
"title":"6. Quản lý con người",
"subtitle":"Giao việc, coaching, phản hồi và phát triển đội ngũ.",
"lessons":[
lesson("6.1","Delegation","Giao việc đi kèm mục tiêu và quyền hạn.",
"Giao việc không phải chỉ chuyển task. Người nhận cần hiểu outcome, phạm vi, deadline, quyền quyết định và điểm check.",
"Dùng cấu trúc: kết quả mong đợi, tiêu chuẩn, deadline, resource, checkpoint và escalation rule.",
"Giao engineer lead trial: mục tiêu, acceptance criteria, budget sample và mốc review được xác định trước.",
"☐ Outcome rõ?\n☐ Quyền hạn đủ?\n☐ Checkpoint hợp lý?"),
lesson("6.2","Coaching","Giúp nhân viên tự tìm cách giải quyết.",
"Coaching khác với ra lệnh ở chỗ manager dùng câu hỏi để tăng năng lực suy nghĩ của người được hướng dẫn.",
"Hỏi: mục tiêu là gì, hiện trạng ra sao, lựa chọn nào có thể thử, bước tiếp theo là gì.",
"Thay vì nói ngay root cause, manager yêu cầu engineer trình bày dữ liệu và ba giả thuyết có khả năng nhất.",
"☐ Đã nghe trước khi hướng dẫn?\n☐ Câu hỏi mở?\n☐ Người được coaching tự chốt action?"),
lesson("6.3","Feedback","Phản hồi cụ thể, đúng thời điểm và hướng tới hành vi.",
"Feedback hiệu quả tập trung vào hành vi quan sát được và tác động của nó, không gắn nhãn con người.",
"Dùng Situation–Behavior–Impact rồi thống nhất hành động tiếp theo.",
"Trong cuộc họp sáng, báo cáo chưa có số liệu baseline nên team khó quyết định. Lần sau hãy bổ sung baseline trước kết luận.",
"☐ Có ví dụ cụ thể?\n☐ Không công kích cá nhân?\n☐ Có next step?"),
lesson("6.4","Skill Matrix","Nhìn năng lực đội ngũ một cách hệ thống.",
"Skill Matrix thể hiện mức năng lực theo kỹ năng và con người, giúp lập kế hoạch đào tạo và backup.",
"Định nghĩa level rõ: biết lý thuyết, làm có hỗ trợ, làm độc lập, có thể đào tạo người khác.",
"Một process chỉ có một engineer level 4 là rủi ro; cần phát triển ít nhất một backup.",
"☐ Level có tiêu chí?\n☐ Có skill critical?\n☐ Có kế hoạch backup?"),
]},

{
"title":"7. Quản lý mục tiêu và KPI",
"subtitle":"Biến mục tiêu thành chỉ số và hành động có thể theo dõi.",
"lessons":[
lesson("7.1","SMART Goal","Đặt mục tiêu cụ thể và có thể kiểm tra.",
"SMART giúp mục tiêu Specific, Measurable, Achievable, Relevant và Time-bound.",
"Viết mục tiêu có baseline, target, deadline và phạm vi.",
"Không viết “giảm defect”; viết “giảm defect A từ 1,2% xuống ≤0,6% trước 30/11 trên line 2”.",
"☐ Có số đo?\n☐ Có deadline?\n☐ Có phạm vi?"),
lesson("7.2","KPI vs Activity","Phân biệt kết quả và hoạt động.",
"KPI đo kết quả quan trọng; activity chỉ là việc đã làm. Hoàn thành nhiều activity không đồng nghĩa đạt outcome.",
"Mỗi KPI nên có driver hoặc action hỗ trợ nhưng không thay KPI bằng số lượng cuộc họp hay số báo cáo.",
"KPI là OEE ≥85%; activity là review downtime hằng ngày.",
"☐ KPI đo outcome?\n☐ Activity có liên hệ nhân quả?\n☐ Có owner?"),
lesson("7.3","Leading & Lagging Indicators","Kết hợp chỉ số sớm và chỉ số kết quả.",
"Lagging indicator cho biết kết quả đã xảy ra; leading indicator cho tín hiệu sớm để can thiệp.",
"Với mỗi KPI kết quả, tìm 1–3 driver có thể theo dõi sớm.",
"Customer claim là lagging; process audit compliance và Cpk critical dimension có thể là leading.",
"☐ Có chỉ số sớm?\n☐ Có hành động khi vượt ngưỡng?\n☐ Có tránh quá nhiều chỉ số?"),
lesson("7.4","KPI Review Cadence","Thiết lập nhịp xem KPI và hành động.",
"KPI chỉ có giá trị khi được review theo nhịp phù hợp với tốc độ biến động của quá trình.",
"Daily cho chỉ số vận hành nhanh, weekly cho action, monthly cho xu hướng và chiến lược.",
"Scrap được theo dõi daily; cost saving được review monthly.",
"☐ Cadence phù hợp?\n☐ Có threshold escalation?\n☐ Review có action owner?"),
]},

{
"title":"8. Giao tiếp – báo cáo – thuyết phục",
"subtitle":"Trình bày ngắn gọn, có logic và hướng tới quyết định.",
"lessons":[
lesson("8.1","Pyramid Principle","Đưa kết luận trước rồi hỗ trợ bằng luận điểm.",
"Pyramid Principle giúp người nghe nắm thông điệp chính trước khi đi vào chi tiết.",
"Bắt đầu bằng kết luận, sau đó 2–4 luận điểm hỗ trợ, cuối cùng mới đi vào bằng chứng.",
"“Đề xuất giữ supplier A” → chất lượng tốt hơn, giá đã tương đương, đã có lịch sử test OK.",
"☐ Kết luận nằm ở đầu?\n☐ Luận điểm không trùng lặp?\n☐ Dữ liệu hỗ trợ từng luận điểm?"),
lesson("8.2","One-page Report","Tóm vấn đề trong một trang có cấu trúc.",
"Một trang tốt buộc người viết chọn điều quan trọng và giúp người đọc ra quyết định nhanh.",
"Dùng khung Background – Current Status – Analysis – Action – Result – Next Step.",
"FACA hoặc improvement summary có thể gói trong một trang thay vì 20 slide.",
"☐ Có message chính?\n☐ Biểu đồ phục vụ câu hỏi?\n☐ Next step rõ?"),
lesson("8.3","Data Storytelling","Biến số liệu thành thông điệp.",
"Data storytelling kết nối context, dữ liệu và quyết định thay vì chỉ đưa bảng số.",
"Cho người đọc biết baseline, thay đổi, nguyên nhân, mức gain và implication.",
"Defect giảm 0,7% sau hai action; biểu đồ trước/sau cho thấy xu hướng ổn định qua 10 ca.",
"☐ Có context?\n☐ Biểu đồ đúng loại?\n☐ Có conclusion từ dữ liệu?"),
lesson("8.4","Meeting Discipline","Tổ chức họp hướng tới quyết định.",
"Họp hiệu quả có mục tiêu, dữ liệu chuẩn bị trước, owner và action rõ.",
"Mỗi agenda ghi loại đầu ra: decision, alignment hay information. Kết thúc bằng action-owner-deadline.",
"Họp root cause 30 phút chỉ tập trung ba giả thuyết đã có dữ liệu, không brainstorm lại từ đầu.",
"☐ Agenda rõ?\n☐ Người cần quyết định có mặt?\n☐ Action được ghi ngay?"),
]},

{
"title":"9. Phát triển năng lực nghề nghiệp",
"subtitle":"Xây năng lực theo lộ trình từ chuyên môn đến lãnh đạo.",
"lessons":[
lesson("9.1","T-shaped Skills","Kết hợp chiều sâu chuyên môn và hiểu biết rộng.",
"T-shaped professional có một trục chuyên môn sâu và khả năng phối hợp rộng với các lĩnh vực liên quan.",
"Chọn 1–2 kỹ năng lõi để đào sâu, đồng thời hiểu đủ về quality, data, project, finance và people.",
"Process engineer có thể sâu về lamination nhưng vẫn cần hiểu DOE, SPC, FMEA và giao tiếp khách hàng.",
"☐ Kỹ năng sâu nhất là gì?\n☐ Kỹ năng ngang còn thiếu?\n☐ Có kế hoạch 6 tháng?"),
lesson("9.2","Deliberate Practice","Luyện tập có mục tiêu thay vì chỉ lặp lại.",
"Deliberate practice cần mục tiêu cụ thể, feedback nhanh và mức thử thách vừa vượt khả năng hiện tại.",
"Chọn một kỹ năng nhỏ, thực hành có đo lường, nhận feedback và điều chỉnh.",
"Muốn giỏi báo cáo, mỗi tuần chọn một slide thật để viết lại theo Pyramid Principle và xin review.",
"☐ Kỹ năng cụ thể?\n☐ Có feedback?\n☐ Có tăng độ khó?"),
lesson("9.3","Learning Loop","Biến công việc thành hệ thống học tập.",
"Mỗi dự án nên tạo ra kiến thức dùng lại được, không chỉ đóng action.",
"Sau mỗi vấn đề: ghi lesson learned, cập nhật standard, checklist hoặc training material.",
"Sau một customer claim, team cập nhật FMEA và thêm kiểm soát vào control plan.",
"☐ Có lesson learned?\n☐ Có cập nhật hệ thống?\n☐ Người khác có thể tái sử dụng?"),
lesson("9.4","Career Portfolio","Quản lý sự nghiệp bằng bằng chứng năng lực.",
"Career portfolio là tập hợp dự án, kết quả, kỹ năng và ảnh hưởng đã tạo ra.",
"Mỗi quý ghi lại 3–5 case: vấn đề, vai trò, cách làm, số liệu kết quả và bài học.",
"Thay vì nói “có kinh nghiệm improvement”, portfolio thể hiện ba dự án với gain cụ thể.",
"☐ Có số liệu kết quả?\n☐ Vai trò cá nhân rõ?\n☐ Có bài học rút ra?"),
]},

{
"title":"10. Hệ thống phương pháp và công cụ thực hành",
"subtitle":"Thư viện mô hình, checklist và công cụ áp dụng nhanh.",
"lessons":[
lesson("10.1","RACI","Làm rõ vai trò trong công việc liên phòng ban.",
"RACI phân biệt Responsible, Accountable, Consulted và Informed.",
"Mỗi deliverable nên có đúng một Accountable; tránh quá nhiều người “cùng chịu trách nhiệm” nhưng không ai quyết định.",
"Trial process: PE Responsible, PE Manager Accountable, QA/PMC Consulted, Production Informed.",
"☐ Có một A rõ ràng?\n☐ R có đủ nguồn lực?\n☐ C/I không bị lạm dụng?"),
lesson("10.2","Risk Matrix","Ưu tiên rủi ro theo xác suất và tác động.",
"Risk Matrix giúp chuyển danh sách rủi ro thành thứ tự ưu tiên hành động.",
"Định nghĩa scale trước, chấm probability và impact, rồi gắn action cho vùng vượt ngưỡng.",
"Thay đổi supplier có xác suất medium nhưng impact customer high nên vẫn cần validation sâu.",
"☐ Scale thống nhất?\n☐ Có owner?\n☐ Có residual risk sau action?"),
lesson("10.3","A3 Thinking","Giải quyết vấn đề trong một câu chuyện logic một trang.",
"A3 là cách kể toàn bộ quá trình problem solving theo luồng: background, current state, target, analysis, countermeasure, follow-up.",
"Không bắt đầu bằng việc trang trí form. Hãy xây logic và dữ liệu trước, sau đó mới cô đọng lên một trang.",
"Một A3 tốt cho phép manager hiểu vấn đề và điểm cần quyết định trong vài phút.",
"☐ Current state có dữ liệu?\n☐ Target rõ?\n☐ Countermeasure nối với root cause?"),
lesson("10.4","Personal Management System","Kết nối mục tiêu, công việc, ghi chú và review.",
"Một hệ thống cá nhân tốt giảm tải trí nhớ và tạo một nơi đáng tin để quản lý cam kết.",
"Dùng bốn lớp: mục tiêu quý, project/action list, calendar và weekly review.",
"Khi nhận task mới, ghi vào hệ thống, xác định deadline và next action thay vì giữ trong đầu.",
"☐ Có một nơi quản lý task?\n☐ Có weekly review?\n☐ Mục tiêu liên kết với hành động?"),
]},
]
