CHAPTERS = [
    {"title":"1. Tư duy đúng trước khi hành động","subtitle":"Nền tảng để nhìn đúng vấn đề trước khi chọn giải pháp.","lessons":[
        {"id":"1.1","title":"Tư duy là gì?","summary":"Hiểu bản chất của tư duy và vai trò của nó trước khi hành động.","content":'''TƯ DUY LÀ GÌ?\n\nTư duy là quá trình tiếp nhận thông tin, đặt câu hỏi, kết nối dữ kiện, hình thành nhận định và lựa chọn hành động. Chất lượng hành động thường phụ thuộc trực tiếp vào chất lượng tư duy trước đó.\n\n1. TƯ DUY KHÔNG CHỈ LÀ “NGHĨ”\nTư duy tốt đòi hỏi chúng ta phân biệt được dữ kiện, giả định và ý kiến. Nếu ba yếu tố này bị trộn lẫn, quyết định dễ bị dẫn dắt bởi cảm tính.\n\n2. NGUYÊN TẮC 3 CÂU HỎI\n• Mình biết chắc điều gì?\n• Mình đang giả định điều gì?\n• Còn dữ liệu nào cần kiểm tra?\n\n3. VÍ DỤ THỰC TẾ\nMột công đoạn có tỷ lệ lỗi tăng. Phản ứng nhanh có thể là quy trách nhiệm cho người vận hành. Tư duy có hệ thống sẽ kiểm tra máy, vật liệu, phương pháp, môi trường và hệ thống đo trước khi kết luận.\n\nBÀI HỌC CHÍNH\nĐừng vội giải quyết vấn đề trước khi xác định đúng vấn đề.'''} ,
        {"id":"1.2","title":"Fact – Opinion – Assumption","summary":"Phân biệt dữ kiện, ý kiến và giả định trong trao đổi công việc.","content":'''FACT – OPINION – ASSUMPTION\n\nFACT – DỮ KIỆN\nLà thông tin có thể kiểm chứng bằng số liệu, hồ sơ, quan sát hoặc bằng chứng cụ thể.\n\nOPINION – Ý KIẾN\nLà cách một người diễn giải hoặc đánh giá sự việc. Ý kiến có thể hữu ích nhưng không nên được trình bày như dữ kiện.\n\nASSUMPTION – GIẢ ĐỊNH\nLà điều chúng ta tạm cho là đúng khi chưa có đủ bằng chứng.\n\nVÍ DỤ\n• Fact: Tỷ lệ NG ngày hôm nay là 2,8%.\n• Opinion: Máy này hoạt động không ổn định.\n• Assumption: Lỗi tăng vì vật liệu của nhà cung cấp mới.\n\nCHECKLIST TRƯỚC KHI HỌP\n☐ Số liệu nào đã được xác nhận?\n☐ Nhận định nào chỉ là ý kiến?\n☐ Giả định nào cần test?\n☐ Ai chịu trách nhiệm xác minh?\n\nBÀI HỌC CHÍNH\nMột cuộc họp hiệu quả bắt đầu bằng việc tách dữ kiện khỏi suy đoán.'''} ,
        {"id":"1.3","title":"Critical Thinking","summary":"Đặt câu hỏi đúng để kiểm tra chất lượng thông tin và kết luận.","content":'''CRITICAL THINKING – TƯ DUY PHẢN BIỆN\n\nTư duy phản biện không có nghĩa là phản đối mọi thứ. Đó là khả năng kiểm tra một lập luận trước khi chấp nhận nó.\n\n5 CÂU HỎI CỐT LÕI\n1. Nguồn thông tin là gì?\n2. Bằng chứng nào hỗ trợ kết luận này?\n3. Có cách giải thích khác không?\n4. Điều gì có thể khiến kết luận sai?\n5. Nếu quyết định sai, rủi ro là gì?\n\nỨNG DỤNG\nKhi nhận một báo cáo “đã cải tiến”, đừng chỉ nhìn kết luận. Hãy kiểm tra baseline, cỡ mẫu, thời gian theo dõi và điều kiện trước/sau cải tiến.\n\nBÀI HỌC CHÍNH\nCâu hỏi tốt thường có giá trị hơn một câu trả lời nhanh.'''}
    ]},
    {"title":"2. Tư duy logic và tư duy hệ thống","subtitle":"Xây dựng chuỗi lập luận rõ ràng và nhìn vấn đề trong toàn hệ thống.","lessons":[
        {"id":"2.1","title":"Logical Thinking","summary":"Sắp xếp thông tin theo chuỗi nguyên nhân – kết quả rõ ràng.","content":'''LOGICAL THINKING\n\nTư duy logic giúp biến một vấn đề phức tạp thành chuỗi lập luận dễ kiểm tra.\n\nCẤU TRÚC CƠ BẢN\nHiện tượng → Dữ kiện → Giả thuyết → Kiểm chứng → Kết luận → Hành động\n\nMột báo cáo logic cần trả lời được:\n• Chuyện gì xảy ra?\n• Xảy ra ở đâu và khi nào?\n• Mức độ bao nhiêu?\n• Nguyên nhân nào đã được xác nhận?\n• Hành động nào xử lý nguyên nhân đó?\n• Kết quả được theo dõi ra sao?\n\nBÀI HỌC CHÍNH\nNếu người đọc không nhìn thấy mối nối giữa dữ liệu và kết luận, báo cáo chưa đủ logic.'''} ,
        {"id":"2.2","title":"System Thinking","summary":"Nhìn vấn đề như một phần của hệ thống thay vì một điểm lỗi riêng lẻ.","content":'''SYSTEM THINKING – TƯ DUY HỆ THỐNG\n\nMột lỗi thường không tồn tại độc lập. Nó có thể là kết quả của nhiều yếu tố tương tác: con người, thiết bị, tiêu chuẩn, dòng thông tin, vật liệu và cách quản lý.\n\nTHAY ĐỔI CÁCH HỎI\nKhông chỉ hỏi: “Ai làm sai?”\nHãy hỏi thêm: “Hệ thống nào cho phép lỗi này xảy ra hoặc lọt qua?”\n\nVÍ DỤ\nOperator đặt sai thông số. Nếu chỉ đào tạo lại operator, lỗi có thể lặp lại. Nếu hệ thống cho phép nhập thông số ngoài spec mà không cảnh báo, đó là một điểm cần cải tiến ở cấp hệ thống.\n\nBÀI HỌC CHÍNH\nGiải pháp mạnh là giải pháp làm cho lỗi khó tái diễn, không chỉ nhắc mọi người cẩn thận hơn.'''}
    ]},
    {"title":"3. Phương pháp giải quyết vấn đề","subtitle":"Từ hiện tượng đến nguyên nhân gốc và hành động có hiệu lực.","lessons":[
        {"id":"3.1","title":"5 Why","summary":"Đi từ hiện tượng đến nguyên nhân gốc bằng chuỗi câu hỏi tại sao.","content":'''5 WHY\n\n5 Why là phương pháp đặt liên tiếp câu hỏi “Tại sao?” nhằm đi sâu từ hiện tượng đến nguyên nhân có thể kiểm soát được. Con số 5 không phải quy định cứng; quan trọng là dừng ở nguyên nhân có bằng chứng và có thể hành động.\n\nVÍ DỤ\nMachine Stop\n↓ Tại sao?\nSensor không detect.\n↓ Tại sao?\nSensor bị lệch vị trí.\n↓ Tại sao?\nBracket bị lỏng.\n↓ Tại sao?\nScrew không được kiểm soát torque.\n↓ Tại sao?\nWI không quy định torque standard.\n\nROOT CAUSE\nThiếu tiêu chuẩn torque trong WI và không có cơ chế xác nhận sau bảo trì.\n\nSAI LẦM THƯỜNG GẶP\n• Dừng ở “operator mistake”.\n• Mỗi câu trả lời không có bằng chứng.\n• Chuỗi Why bị nhảy logic.\n• Action không liên hệ trực tiếp với root cause.\n\nCHECKLIST\n☐ Có dữ kiện cho mỗi Why?\n☐ Root cause có thể kiểm soát?\n☐ Action ngăn tái diễn?\n☐ Có kế hoạch xác nhận hiệu quả?'''} ,
        {"id":"3.2","title":"PDCA","summary":"Chu trình cải tiến liên tục từ lập kế hoạch đến chuẩn hóa.","content":'''PDCA – PLAN / DO / CHECK / ACT\n\nPLAN\nXác định vấn đề, mục tiêu, nguyên nhân và kế hoạch hành động.\n\nDO\nThực hiện thử nghiệm hoặc hành động trong phạm vi có kiểm soát.\n\nCHECK\nSo sánh kết quả với mục tiêu bằng dữ liệu.\n\nACT\nNếu hiệu quả: chuẩn hóa. Nếu chưa hiệu quả: cập nhật giả thuyết và quay lại Plan.\n\nĐIỂM QUAN TRỌNG\nPDCA không phải bốn ô để điền cho đủ báo cáo. Giá trị nằm ở việc biến cải tiến thành một vòng học tập liên tục.\n\nBÀI HỌC CHÍNH\nCải tiến chưa hoàn thành cho đến khi kết quả được xác nhận và cách làm mới được chuẩn hóa.'''}
    ]},
    {"title":"4. Ra quyết định dựa trên dữ liệu","subtitle":"Đánh giá dữ liệu, rủi ro và phương án trước khi quyết định.","lessons":[]},
    {"title":"5. Quản lý công việc và thời gian","subtitle":"Ưu tiên đúng, quản lý tải công việc và duy trì nhịp thực thi.","lessons":[]},
    {"title":"6. Quản lý con người","subtitle":"Giao việc, coaching, phản hồi và phát triển đội ngũ.","lessons":[]},
    {"title":"7. Quản lý mục tiêu và KPI","subtitle":"Biến mục tiêu thành chỉ số và hành động có thể theo dõi.","lessons":[]},
    {"title":"8. Giao tiếp – báo cáo – thuyết phục","subtitle":"Trình bày ngắn gọn, có logic và hướng tới quyết định.","lessons":[]},
    {"title":"9. Phát triển năng lực nghề nghiệp","subtitle":"Xây năng lực theo lộ trình từ chuyên môn đến lãnh đạo.","lessons":[]},
    {"title":"10. Hệ thống phương pháp và công cụ thực hành","subtitle":"Thư viện mô hình, checklist và công cụ áp dụng nhanh.","lessons":[]},
]
