def lesson(i, title, summary, concept, method, example, checklist, blocks, style,
           why="", mistakes=None, practice="", reflect=None):
    return {
        "id": i,
        "title": title or "",
        "summary": summary or "",
        "concept": concept or "",
        "method": method or "",
        "example": example or "",
        "checklist": checklist or [],
        "blocks": blocks or [],
        "style": style or "flow",
        "why": why or "",
        "mistakes": mistakes or [],
        "practice": practice or "",
        "reflect": reflect or [],
    }

def L(i,t,s,c,m,e,blocks,style,why="",mis=None,p="",r=None):
    # The lesson calls use: blocks, style, why, mistakes, practice, reflect.
    # Build a practical checklist automatically so the data schema remains complete.
    safe_blocks = blocks if isinstance(blocks, list) else []
    checklist = []
    for item in safe_blocks[:3]:
        if isinstance(item, (list, tuple)) and item:
            checklist.append(f"Đã xác định rõ {str(item[0]).lower()} chưa?")
    checklist.append("Đã có dữ liệu hoặc ví dụ thực tế để kiểm chứng chưa?")
    return lesson(i,t,s,c,m,e,checklist,safe_blocks,style,why,mis,p,r)

CHAPTERS=[
{"title":"1. Tư duy đúng trước khi hành động","subtitle":"Nhìn đúng vấn đề trước khi chọn giải pháp.","lessons":[
L("1.1","Tư duy là gì?","Biến thông tin thành quyết định có chất lượng.",
"Tư duy là quá trình tiếp nhận thông tin, đặt câu hỏi, kết nối dữ kiện, hình thành nhận định và lựa chọn hành động.",
"Trước một vấn đề, hãy tách ba lớp: điều đã biết, điều đang giả định và điều cần kiểm tra.",
"Một công đoạn tăng lỗi. Thay vì quy trách nhiệm ngay cho operator, nhóm kiểm tra máy, vật liệu, phương pháp, ca và hệ thống đo.",
[("DỮ KIỆN","Điều đã biết chắc"),("CÂU HỎI","Điều cần làm rõ"),("HÀNH ĐỘNG","Quyết định sau khi hiểu")],"flow",
"Tư duy tốt giúp tránh hành động nhanh nhưng sai hướng. Trong quản lý, chi phí lớn thường không đến từ thiếu hành động mà từ hành động dựa trên nhận định sai.",
["Nhảy từ hiện tượng sang giải pháp","Đồng nhất kinh nghiệm với sự thật","Không kiểm tra giả định"],
"Chọn một vấn đề đang xử lý và viết 3 cột: Fact / Assumption / Need to verify.",
["Điều gì tôi biết chắc?","Điều gì chỉ là suy đoán?","Bằng chứng nào có thể làm tôi đổi ý?"]),
L("1.2","Fact – Opinion – Assumption","Phân biệt dữ kiện, ý kiến và giả định.",
"Fact có thể kiểm chứng; Opinion là cách diễn giải; Assumption là điều tạm cho là đúng khi chưa đủ bằng chứng.",
"Khi họp hoặc viết báo cáo, gắn nhãn rõ từng loại thông tin. Chỉ dùng Fact làm nền cho kết luận chính.",
"Fact: NG 2,8%. Opinion: máy không ổn định. Assumption: lỗi tăng do vật liệu nhà cung cấp mới.",
[("FACT","Dữ kiện kiểm chứng được"),("OPINION","Cách diễn giải, ý kiến"),("ASSUMPTION","Giả định chưa đủ bằng chứng")],"flow",
"Nhiều tranh luận kéo dài vì người tham gia đang bảo vệ Opinion hoặc Assumption như thể đó là Fact.",
["Dùng từ chắc chắn cho giả định","Không chỉ ra nguồn số liệu","Biến nhận xét cá nhân thành kết luận"],
"Trong cuộc họp tiếp theo, đánh dấu F/O/A bên cạnh từng nhận định quan trọng.",
["Câu nào có thể kiểm chứng ngay?","Câu nào cần test thêm?","Nếu bỏ Opinion đi, kết luận còn đứng vững không?"]),
L("1.3","Critical Thinking","Kiểm tra chất lượng của thông tin và kết luận.",
"Tư duy phản biện là khả năng kiểm tra một lập luận trước khi chấp nhận, không phải phản đối mọi thứ.",
"Hỏi về nguồn dữ liệu, bằng chứng, cách giải thích khác, rủi ro sai và điều kiện khiến kết luận không còn đúng.",
"Một báo cáo nói action đã hiệu quả. Kiểm tra lại baseline, cỡ mẫu và thời gian theo dõi cho thấy kết luận được đưa ra quá sớm.",
[("NGUỒN","Thông tin đến từ đâu?"),("BẰNG CHỨNG","Điều gì chứng minh?"),("RỦI RO","Nếu sai thì sao?")],"steps",
"Nó giúp nhóm không bị dẫn dắt bởi người nói tự tin nhất, dữ liệu đẹp nhất hoặc câu chuyện nghe hợp lý nhất.",
["Chỉ tìm bằng chứng ủng hộ","Không xem giả thuyết thay thế","Dùng một ví dụ để suy rộng"],
"Chọn một kết luận gần đây và viết ít nhất 2 cách giải thích thay thế.",
["Nguồn dữ liệu có độc lập không?","Mẫu đủ đại diện chưa?","Có dữ kiện nào đang bị bỏ qua?"]),
L("1.4","First Principles Thinking","Tách vấn đề về những yếu tố cơ bản nhất.",
"First Principles bắt đầu từ điều thật sự đúng, thay vì mặc định cách làm hiện tại là bắt buộc.",
"Liệt kê các giả định, bóc tách chúng, giữ lại ràng buộc thật sự rồi thiết kế lại giải pháp từ gốc.",
"Một công đoạn luôn dùng hai người vì lịch sử. Phân tích thao tác cho thấy chỉ một bước cần hai người, phần còn lại có thể thiết kế lại.",
[("GIẢ ĐỊNH CŨ","Thói quen đang tồn tại"),("BẢN CHẤT","Điều thật sự cần"),("THIẾT KẾ MỚI","Cách làm tốt hơn")],"compare",
"Nó đặc biệt hữu ích khi tối ưu chi phí, năng suất hoặc thiết kế quy trình đã tồn tại lâu năm.",
["Coi lịch sử là ràng buộc","Sao chép benchmark không hiểu bản chất","Thiết kế mới nhưng giữ nguyên mọi giả định"],
"Chọn một quy trình quen thuộc và hỏi: nếu hôm nay thiết kế từ đầu, ta có làm y như vậy không?",
["Điều gì bắt buộc bởi vật lý/quy định?","Điều gì chỉ là thói quen?","Có thể loại bỏ bước nào?"])]},
{"title":"2. Tư duy logic và tư duy hệ thống","subtitle":"Xây chuỗi lập luận rõ ràng và nhìn toàn hệ thống.","lessons":[
L("2.1","Logical Thinking","Sắp xếp thông tin thành chuỗi nguyên nhân – kết quả.",
"Tư duy logic giúp biến vấn đề phức tạp thành chuỗi lập luận có thể kiểm tra.",
"Dùng luồng: hiện tượng → dữ kiện → giả thuyết → kiểm chứng → kết luận → hành động.",
"Yield giảm; dữ liệu chỉ ra lỗi tập trung ở một máy; test xác nhận regulator áp lực là nguyên nhân.",
[("HIỆN TƯỢNG","Chuyện gì xảy ra?"),("PHÂN TÍCH","Dữ kiện và giả thuyết"),("KẾT LUẬN","Nguyên nhân và action")],"flow",
"Logic tốt giúp báo cáo ngắn hơn nhưng thuyết phục hơn vì người đọc nhìn thấy cách dữ liệu dẫn tới quyết định.",
["Nhảy bước trong lập luận","Kết luận không có bằng chứng","Action không nối với nguyên nhân"],
"Viết một vấn đề theo đúng 6 bước và kiểm tra xem có bước nào chỉ dựa trên cảm giác.",
["Người khác có theo được chuỗi logic không?","Mỗi mũi tên có bằng chứng không?"]),
L("2.2","System Thinking","Nhìn vấn đề như một phần của hệ thống.",
"Một lỗi thường là kết quả tương tác giữa con người, thiết bị, tiêu chuẩn, vật liệu, đo lường và quản lý.",
"Không chỉ hỏi ai làm sai; hãy hỏi hệ thống nào cho phép lỗi xảy ra hoặc lọt qua.",
"Operator nhập sai thông số; máy lại cho phép nhập ngoài spec mà không cảnh báo.",
[("CON NGƯỜI","Thao tác/nhận thức"),("QUÁ TRÌNH","Tiêu chuẩn/kiểm soát"),("KẾT QUẢ","Lỗi xảy ra/escape")],"cycle",
"System Thinking chuyển trọng tâm từ chữa triệu chứng sang thay đổi điều kiện tạo ra hành vi và kết quả.",
["Chỉ đào tạo lại operator","Chỉ sửa điểm phát hiện lỗi","Không xem tương tác giữa các yếu tố"],
"Với một lỗi lặp lại, vẽ ít nhất 5 yếu tố hệ thống có thể góp phần tạo lỗi.",
["Nếu thay người khác, lỗi còn có thể xảy ra không?","Hệ thống nào nên được thiết kế để khó sai hơn?"]),
L("2.3","MECE","Phân nhóm đầy đủ nhưng không chồng chéo.",
"MECE là nguyên tắc chia vấn đề thành các nhóm không trùng nhau nhưng bao phủ đủ phạm vi.",
"Chọn một trục phân nhóm nhất quán: theo máy, model, ca, công đoạn hoặc loại lỗi.",
"Trộn Machine 1, Night Shift và Model A trong cùng một danh sách sẽ làm phân tích rối vì đó là ba trục khác nhau.",
[("KHÔNG TRÙNG","Mutually Exclusive"),("ĐỦ BAO PHỦ","Collectively Exhaustive"),("DỄ PHÂN TÍCH","Một tiêu chí nhất quán")],"matrix",
"MECE giúp tránh double-count và bỏ sót, đặc biệt khi breakdown dữ liệu lớn.",
["Trộn nhiều tiêu chí phân nhóm","Nhóm Other quá lớn","Một lỗi nằm ở nhiều nhóm"],
"Tạo lại Pareto hiện tại theo một tiêu chí MECE và so sánh độ rõ của kết quả.",
["Có phần nào bị đếm hai lần?","Other có đang che mất một nhóm quan trọng không?"]),
L("2.4","Cause – Effect Mapping","Vẽ bản đồ nguyên nhân và tác động.",
"Cause–Effect Mapping cho thấy một kết quả có thể do nhiều driver và các driver có thể tương tác.",
"Đặt outcome ở trung tâm, nối các driver chính, rồi dùng dữ liệu xác nhận quan hệ.",
"Scrap tăng có thể liên quan material variation, machine setting và detection escape.",
[("OUTCOME","Điều cần giải thích"),("DRIVERS","Nguyên nhân khả dĩ"),("EVIDENCE","Bằng chứng xác nhận")],"steps",
"Phương pháp này hữu ích khi vấn đề không thể giải thích bằng một root cause đơn lẻ.",
["Nhầm tương quan với nhân quả","Liệt kê quá nhiều nhánh không ưu tiên","Không xác nhận bằng dữ liệu"],
"Vẽ cause-effect map cho một KPI đang xấu và khoanh 3 driver có thể kiểm tra trong tuần.",
["Driver nào có ảnh hưởng lớn nhất?","Có interaction nào giữa các driver?"])]},
{"title":"3. Phương pháp giải quyết vấn đề","subtitle":"Từ hiện tượng đến nguyên nhân gốc và hành động có hiệu lực.","lessons":[
L("3.1","5 Why","Đi từ hiện tượng đến nguyên nhân gốc.",
"5 Why đặt câu hỏi Tại sao liên tiếp để đi từ symptom đến nguyên nhân có thể kiểm soát.",
"Mỗi câu trả lời phải có bằng chứng; dừng khi tìm được nguyên nhân hệ thống có thể action.",
"Machine stop → sensor lệch → bracket lỏng → screw không kiểm soát torque → WI thiếu tiêu chuẩn torque.",
[("WHY 1","Hiện tượng trực tiếp"),("WHY 2–4","Đào sâu cơ chế"),("ROOT CAUSE","Nguyên nhân có thể kiểm soát")],"ladder",
"5 Why mạnh ở tính đơn giản nhưng chỉ hiệu quả khi chuỗi Why dựa trên evidence, không phải storytelling.",
["Dừng ở Operator mistake","Nhảy logic giữa các Why","Gắn action trước khi root cause được xác nhận"],
"Lấy một vấn đề thật và yêu cầu mỗi Why phải có cột Evidence bên cạnh.",
["Nếu đổi operator, lỗi có còn không?","Root cause có giải thích được toàn bộ hiện tượng không?"]),
L("3.2","Fishbone","Mở rộng góc nhìn nguyên nhân theo nhóm.",
"Fishbone giúp brainstorm nguyên nhân theo Man, Machine, Material, Method, Measurement, Environment.",
"Dùng sơ đồ để mở rộng khả năng rồi xác nhận từng nhánh bằng dữ liệu.",
"Defect tăng có thể liên quan pressure, thickness, setup, measurement bias hoặc handling.",
[("MAN","Con người"),("MACHINE","Thiết bị"),("MATERIAL","Vật liệu")],"steps",
"Fishbone giảm nguy cơ team khóa quá sớm vào một giả thuyết quen thuộc.",
["Coi brainstorm là root cause","Liệt kê chung chung","Không ưu tiên nhánh để test"],
"Sau khi brainstorm, gắn cho mỗi nguyên nhân: Evidence / Owner / Test.",
["Nhánh nào có evidence mạnh nhất?","Nhánh nào dễ test nhanh nhất?"]),
L("3.3","Pareto","Tập trung vào số ít nguyên nhân tạo phần lớn tác động.",
"Pareto xếp hạng các nhóm lỗi theo tần suất hoặc impact để ưu tiên nguồn lực.",
"Chuẩn hóa phân loại trước khi vẽ và cân nhắc thêm severity, cost hoặc customer risk.",
"Ba defect chiếm 78% tổng NG; team ưu tiên hai lỗi đầu để tạo gain lớn nhất.",
[("TẤT CẢ LỖI","Danh sách ban đầu"),("TOP ÍT","Nhóm ưu tiên"),("IMPACT LỚN","Tập trung nguồn lực")],"steps",
"Pareto giúp team tránh phân tán nguồn lực vào nhiều vấn đề nhỏ cùng lúc.",
["Category không nhất quán","Chỉ nhìn count bỏ qua severity","Dữ liệu từ kỳ không tương đương"],
"Vẽ Pareto theo cả Count và Cost rồi so sánh ưu tiên.",
["Top defect có thật sự là top impact không?","Có lỗi hiếm nhưng risk cao không?"]),
L("3.4","PDCA","Chu trình cải tiến liên tục.",
"PDCA gồm Plan, Do, Check, Act và biến cải tiến thành vòng học tập.",
"Lập giả thuyết, thử trong phạm vi kiểm soát, đo kết quả, sau đó chuẩn hóa hoặc điều chỉnh.",
"Thay đổi parameter trên một máy, theo dõi 3 ngày, so baseline rồi mới rollout toàn line.",
[("PLAN","Xác định vấn đề"),("DO","Thử nghiệm"),("CHECK","Đo kết quả"),("ACT","Chuẩn hóa")],"cycle",
"PDCA ngăn việc rollout giải pháp dựa trên cảm giác và giúp cải tiến có cơ chế học.",
["Do trước khi Plan đủ rõ","Check bằng cảm nhận","Có gain nhưng không chuẩn hóa"],
"Chọn một action hiện tại và viết tiêu chí Pass/Fail trước khi thực hiện.",
["Nếu kết quả không đạt, ta học được gì?","Action tốt sẽ được đưa vào standard nào?"])]},
{"title":"4. Ra quyết định dựa trên dữ liệu","subtitle":"Đánh giá dữ liệu, rủi ro và phương án trước khi quyết định.","lessons":[
L("4.1","Data before Decision","Ưu tiên bằng chứng trước cảm tính.",
"Quyết định tốt cần đủ dữ liệu để giảm rủi ro chính, không nhất thiết chờ dữ liệu hoàn hảo.",
"Xác định câu hỏi quyết định trước rồi thu đúng dữ liệu cần thiết.",
"Chọn supplier cần xem quality, delivery, capacity, risk và cost chứ không chỉ price.",
[("CÂU HỎI","Cần quyết định gì?"),("DỮ LIỆU","Bằng chứng liên quan"),("QUYẾT ĐỊNH","Phương án được chọn")],"flow",
"Nó giúp tránh hai cực: quyết định quá sớm và trì hoãn vô tận vì muốn thêm dữ liệu.",
["Thu nhiều dữ liệu nhưng không trả lời câu hỏi","Dùng dữ liệu lịch sử không tương đương","Chọn metric tiện đo hơn metric quan trọng"],
"Trước quyết định lớn, viết 3 dữ liệu bắt buộc và 3 dữ liệu Nice-to-have.",
["Dữ liệu nào nếu thay đổi sẽ làm tôi đổi quyết định?","Tôi đang thiếu dữ liệu hay thiếu can đảm quyết định?"]),
L("4.2","Baseline & Target","Đặt điểm xuất phát và mục tiêu rõ.",
"Baseline mô tả hiện trạng; Target định nghĩa trạng thái cần đạt.",
"Chốt kỳ baseline đại diện, metric, scope và deadline trước khi đánh giá gain.",
"Defect baseline 1,4%; target ≤0,7% trong 4 tuần trên cùng model mix.",
[("BASELINE","Đang ở đâu?"),("TARGET","Muốn tới đâu?"),("GAP","Cần cải thiện bao nhiêu?")],"compare",
"Không có baseline đáng tin, mọi tuyên bố cải tiến đều yếu vì không biết điều kiện so sánh.",
["Chọn baseline quá ngắn","Target không có deadline","So hai giai đoạn khác model mix"],
"Với một KPI, ghi rõ Baseline period / Target / Scope / Measurement rule.",
["Baseline có đại diện cho normal condition không?","Target có đủ thách thức nhưng khả thi không?"]),
L("4.3","Decision Matrix","So sánh phương án theo tiêu chí có trọng số.",
"Decision Matrix giúp so sánh nhiều phương án bằng cùng bộ tiêu chí và trọng số.",
"Liệt kê tiêu chí, trọng số, chấm điểm, tính tổng và kiểm tra sensitivity.",
"Supplier A giá thấp nhưng delivery risk cao; B ổn định hơn. Ma trận làm trade-off minh bạch.",
[("TIÊU CHÍ","Giá / quality / delivery"),("TRỌNG SỐ","Mức quan trọng"),("ĐIỂM","So sánh phương án")],"matrix",
"Ma trận không thay người quản lý quyết định nhưng làm rõ giả định nằm phía sau quyết định.",
["Gán trọng số theo cảm tính","Tiêu chí trùng nhau","Không test sensitivity"],
"Thay đổi trọng số ±20% và xem phương án thắng có đổi không.",
["Tiêu chí nào đang quyết định kết quả?","Nếu trọng số thay đổi, quyết định có ổn định không?"]),
L("4.4","Risk-based Decision","Ra quyết định theo xác suất và mức hậu quả.",
"Rủi ro kết hợp khả năng xảy ra và mức tác động; sự kiện hiếm nhưng hậu quả lớn vẫn đáng ưu tiên.",
"Đánh giá probability, severity, control hiện tại và residual risk.",
"Thay đổi process có gain nhỏ nhưng customer escape risk cao nên cần validation sâu.",
[("XÁC SUẤT","Khả năng xảy ra"),("TÁC ĐỘNG","Mức hậu quả"),("CONTROL","Cách giảm risk")],"matrix",
"Risk-based thinking giúp không đánh đổi an toàn, chất lượng hoặc khách hàng chỉ vì gain ngắn hạn.",
["Chỉ nhìn probability","Không xem residual risk","Chấm risk sau khi đã thích một phương án"],
"Viết Worst case / Existing control / Residual risk cho một thay đổi đang cân nhắc.",
["Ai có quyền chấp nhận residual risk?","Control giảm probability hay severity?"])]},
{"title":"5. Quản lý công việc và thời gian","subtitle":"Ưu tiên đúng, quản lý tải và duy trì nhịp thực thi.","lessons":[
L("5.1","Eisenhower Matrix","Phân biệt việc quan trọng và khẩn cấp.",
"Ma trận chia việc thành 4 nhóm theo Important và Urgent.",
"Làm ngay việc quan trọng-khẩn; lên lịch việc quan trọng-chưa khẩn; ủy quyền hoặc loại bỏ phần còn lại.",
"Line stop là khẩn và quan trọng; xây skill matrix quý sau quan trọng nhưng chưa khẩn.",
[("LÀM NGAY","Quan trọng + khẩn"),("LÊN LỊCH","Quan trọng + chưa khẩn"),("ỦY QUYỀN","Ít quan trọng hơn")],"matrix",
"Nó bảo vệ thời gian cho việc chiến lược trước khi những việc đó biến thành khủng hoảng.",
["Đồng nhất khẩn cấp với quan trọng","Không chặn lịch cho việc quan trọng","Giữ quá nhiều việc có thể ủy quyền"],
"Phân loại toàn bộ task tuần này vào 4 ô và loại ít nhất 10% việc ít giá trị.",
["Việc nào tạo impact dài hạn?","Việc nào chỉ ồn ào vì người khác thúc?"]),
L("5.2","Time Blocking","Bảo vệ thời gian tập trung.",
"Time Blocking đặt trước khung thời gian cho nhóm công việc thay vì phản ứng liên tục.",
"Chặn 60–90 phút deep work, gom email/họp và giữ buffer cho phát sinh.",
"Engineer dành 9:00–10:30 phân tích DOE thay vì vừa làm vừa trả lời chat.",
[("BLOCK","Đặt thời gian trước"),("FOCUS","Một loại việc"),("BUFFER","Khoảng dự phòng")],"steps",
"Deep work cần được bảo vệ như một cuộc họp quan trọng, nếu không lịch sẽ bị việc vụn chiếm hết.",
["Lịch kín 100%","Block nhưng vẫn mở notification","Không phân biệt deep work và admin work"],
"Chặn 2 block deep work trong tuần tới và tắt notification trong block.",
["Khung giờ năng lượng cao của tôi là khi nào?","Việc nào thực sự cần uninterrupted time?"]),
L("5.3","WIP Limit","Giới hạn số việc đang làm.",
"WIP cao làm tăng context switching và kéo dài lead time.",
"Đặt giới hạn nhiệm vụ active; hoàn thành trước khi kéo thêm việc mới.",
"Một engineer giữ tối đa 3 action active; việc mới vào backlog nếu chưa giải phóng capacity.",
[("BACKLOG","Việc chờ"),("IN PROGRESS","Giới hạn WIP"),("DONE","Hoàn thành trước khi kéo thêm")],"flow",
"WIP Limit làm lộ bottleneck và buộc team ưu tiên thật sự thay vì gọi mọi thứ là priority.",
["Mở quá nhiều task","Không có Definition of Done","Thêm việc mới mà không bỏ việc cũ"],
"Đếm số việc active hiện tại và đặt WIP limit thấp hơn 20–30%.",
["Task nào đã mở quá lâu?","Có việc nào nên đóng hoặc hủy?"]),
L("5.4","Weekly Review","Duy trì nhịp xem lại và điều chỉnh.",
"Weekly Review nối kế hoạch với thực tế bằng một chu kỳ nhìn lại – điều chỉnh – cam kết.",
"Mỗi tuần xem goal, task done, task trễ, blocker, lesson và top priority.",
"30 phút thứ Sáu giúp phát hiện action thiếu owner hoặc deadline trước khi thành vấn đề.",
[("NHÌN LẠI","Đã làm gì?"),("ĐIỀU CHỈNH","Cần đổi gì?"),("CAM KẾT","Tuần tới tập trung gì?")],"cycle",
"Nếu không review, task system dần mất tin cậy và não lại quay về nhớ bằng đầu.",
["Chỉ nhìn task chưa làm","Không review calendar và goal","Không đóng việc không còn giá trị"],
"Đặt lịch 30 phút cố định mỗi tuần và dùng checklist review giống nhau.",
["Tuần qua tôi tạo impact gì?","Có commitment nào đang bị quên?"])]},
{"title":"6. Quản lý con người","subtitle":"Giao việc, coaching, feedback và phát triển đội ngũ.","lessons":[
L("6.1","Delegation","Giao việc kèm mục tiêu và quyền hạn.",
"Delegation tốt chuyển cả trách nhiệm thực thi và mức quyền phù hợp, không chỉ chuyển task.",
"Làm rõ outcome, standard, deadline, resource, checkpoint và escalation rule.",
"Giao lead trial nhưng không rõ acceptance criteria khiến engineer làm nhiều mà vẫn lệch kỳ vọng.",
[("OUTCOME","Kết quả cần đạt"),("AUTHORITY","Được quyết gì?"),("CHECKPOINT","Khi nào review?")],"steps",
"Delegation vừa giải phóng thời gian manager vừa phát triển năng lực người nhận.",
["Giao task nhưng giữ mọi quyết định","Micromanage giữa chừng","Không nói rõ tiêu chuẩn Done"],
"Chọn một việc bạn đang giữ và giao theo mẫu Outcome / Authority / Checkpoint.",
["Người nhận có đủ context không?","Tôi đang kiểm soát vì risk thật hay vì thói quen?"]),
L("6.2","Coaching","Giúp nhân viên tự tìm cách giải quyết.",
"Coaching dùng câu hỏi để phát triển năng lực suy nghĩ thay vì đưa đáp án ngay.",
"Hỏi Goal – Reality – Options – Way Forward và để người được coaching tự cam kết action.",
"Manager yêu cầu engineer trình bày dữ liệu và 3 giả thuyết trước khi góp ý root cause.",
[("GOAL","Muốn đạt gì?"),("REALITY","Đang ở đâu?"),("OPTIONS","Có lựa chọn nào?")],"steps",
"Coaching tạo năng lực dài hạn; chỉ dẫn trực tiếp tạo tốc độ ngắn hạn nhưng dễ lệ thuộc.",
["Hỏi nhưng đã có sẵn câu trả lời","Cắt lời quá sớm","Biến coaching thành đánh giá"],
"Trong một cuộc 1:1, chỉ dùng câu hỏi trong 10 phút đầu trước khi đưa lời khuyên.",
["Người kia học cách nghĩ hay chỉ nhận đáp án?","Câu hỏi nào làm họ nhìn vấn đề khác đi?"]),
L("6.3","Feedback","Phản hồi cụ thể và hướng tới hành vi.",
"Feedback hiệu quả mô tả Situation – Behavior – Impact thay vì gắn nhãn con người.",
"Đưa feedback gần thời điểm xảy ra, cụ thể và có next step.",
"Trong cuộc họp sáng, báo cáo thiếu baseline nên team khó quyết định; lần sau cần bổ sung baseline trước conclusion.",
[("SITUATION","Hoàn cảnh"),("BEHAVIOR","Hành vi quan sát"),("IMPACT","Tác động")],"flow",
"Feedback cụ thể giúp người nhận biết điều gì cần lặp lại hoặc thay đổi, giảm phòng thủ.",
["Dùng từ luôn luôn/không bao giờ","Phê bình tính cách","Feedback quá muộn"],
"Viết một feedback theo SBI và bỏ toàn bộ tính từ đánh giá con người.",
["Tôi đang mô tả hành vi hay phán xét tính cách?","Người nhận có biết bước tiếp theo không?"]),
L("6.4","Skill Matrix","Quản lý năng lực đội ngũ có hệ thống.",
"Skill Matrix thể hiện mức năng lực theo người và kỹ năng, giúp xác định gap và backup.",
"Định nghĩa level: biết lý thuyết, làm có hỗ trợ, làm độc lập, có thể đào tạo người khác.",
"Một process chỉ có một engineer Level 4 là rủi ro continuity.",
[("LEVEL 1","Biết lý thuyết"),("LEVEL 2–3","Làm được"),("LEVEL 4","Dẫn dắt/đào tạo")],"ladder",
"Nó biến đào tạo từ hoạt động chung chung thành kế hoạch năng lực có mục tiêu.",
["Level không có tiêu chí","Ai cũng tự đánh giá quá cao","Không gắn skill critical với backup"],
"Chọn 10 kỹ năng critical và đánh giá team bằng tiêu chí hành vi cụ thể.",
["Skill nào chỉ có một người biết?","Gap nào ảnh hưởng kế hoạch 6 tháng tới?"])]},
{"title":"7. Quản lý mục tiêu và KPI","subtitle":"Biến mục tiêu thành chỉ số và action theo dõi được.","lessons":[
L("7.1","SMART Goal","Đặt mục tiêu cụ thể và kiểm tra được.",
"SMART giúp mục tiêu Specific, Measurable, Achievable, Relevant và Time-bound.",
"Viết mục tiêu có baseline, target, scope, owner và deadline.",
"Giảm defect A từ 1,2% xuống ≤0,6% trước 30/11 trên line 2.",
[("SPECIFIC","Cụ thể"),("MEASURABLE","Đo được"),("TIME-BOUND","Có thời hạn")],"steps",
"Mục tiêu rõ giảm tranh cãi về trạng thái hoàn thành và giúp team tự ưu tiên.",
["Target không có baseline","Không có deadline","Đo activity thay vì result"],
"Viết lại một goal hiện tại theo Baseline → Target → Scope → Deadline.",
["Người khác đọc có hiểu giống tôi không?","Có điều kiện đo nào cần giữ cố định?"]),
L("7.2","KPI vs Activity","Phân biệt kết quả và hoạt động.",
"KPI đo outcome; Activity là việc thực hiện để tác động outcome.",
"Giữ KPI ít và liên kết mỗi KPI với 1–3 driver/action có logic nhân quả.",
"KPI: OEE ≥85%. Activity: review downtime daily.",
[("KPI","Kết quả đầu ra"),("ACTIVITY","Việc thực hiện"),("LINK","Quan hệ nhân quả")],"compare",
"Phân biệt hai khái niệm giúp tổ chức tránh cảm giác bận rộn nhưng không tạo kết quả.",
["Dùng số cuộc họp làm KPI","Đo activity vì dễ đo","Không kiểm tra activity có tác động KPI không"],
"Với một KPI, liệt kê 3 activity và giải thích cơ chế tác động.",
["KPI nào hiện chỉ đang đo mức độ bận?","Activity nào có thể dừng mà outcome không đổi?"]),
L("7.3","Leading & Lagging Indicators","Kết hợp chỉ số sớm và chỉ số kết quả.",
"Lagging cho biết kết quả đã xảy ra; Leading cho tín hiệu sớm để can thiệp.",
"Với mỗi KPI kết quả, xác định 1–3 leading driver và threshold hành động.",
"Customer claim là lagging; audit compliance và Cpk critical dimension có thể là leading.",
[("LEADING","Cảnh báo sớm"),("LAGGING","Kết quả đã xảy ra"),("ACTION","Can thiệp theo ngưỡng")],"flow",
"Leading indicators cho team cơ hội hành động trước khi hậu quả xuất hiện.",
["Chọn chỉ số không thật sự leading","Quá nhiều chỉ số","Không có action rule khi vượt ngưỡng"],
"Chọn một lagging KPI và viết 2 leading indicator + threshold + action.",
["Tín hiệu nào xuất hiện sớm nhất?","Nếu chỉ số xấu, team biết làm gì ngay không?"]),
L("7.4","KPI Review Cadence","Thiết lập nhịp review phù hợp.",
"KPI cần được review theo tốc độ biến động: Daily, Weekly hoặc Monthly.",
"Daily cho operation nhanh; Weekly cho action; Monthly cho trend và quyết định quản trị.",
"Scrap review daily; cost saving review monthly.",
[("DAILY","Biến động nhanh"),("WEEKLY","Action progress"),("MONTHLY","Xu hướng/chiến lược")],"steps",
"Cadence đúng biến KPI thành hệ điều hành; cadence sai tạo noise hoặc phản ứng quá muộn.",
["Review mọi KPI cùng tần suất","Chỉ đọc số không chốt action","Meeting KPI quá dài"],
"Phân loại KPI hiện tại thành Daily / Weekly / Monthly và loại review trùng lặp.",
["KPI nào đang review quá thường xuyên?","Meeting có tạo quyết định hay chỉ đọc số?"])]},
{"title":"8. Giao tiếp – báo cáo – thuyết phục","subtitle":"Trình bày ngắn gọn, có logic và hướng tới quyết định.","lessons":[
L("8.1","Pyramid Principle","Đưa kết luận trước rồi hỗ trợ bằng luận điểm.",
"Pyramid Principle tổ chức thông tin theo Conclusion → Reasons → Evidence.",
"Bắt đầu bằng điều muốn người nghe hiểu hoặc quyết định, sau đó mới đi sâu chi tiết.",
"Đề xuất giữ supplier A → quality tốt hơn, giá đã tương đương, lịch sử test OK.",
[("CONCLUSION","Thông điệp chính"),("REASONS","Lý do hỗ trợ"),("EVIDENCE","Số liệu/chứng cứ")],"ladder",
"Nó phù hợp với manager vì người nghe thường không có thời gian chờ đến slide cuối mới biết kết luận.",
["Kể lịch sử quá dài","Luận điểm trùng nhau","Biểu đồ không gắn message"],
"Viết lại một slide theo 3 tầng Conclusion / 3 Reasons / Evidence.",
["Nếu chỉ có 30 giây, người nghe hiểu gì?","Mỗi biểu đồ trả lời câu hỏi nào?"]),
L("8.2","One-page Report","Tóm vấn đề trong một trang logic.",
"One-page Report ép người viết chọn điều quan trọng và tạo một luồng đọc nhanh.",
"Dùng Background – Current – Analysis – Action – Result – Next Step.",
"Một FACA tốt có thể gói trong 1 trang thay vì 20 slide rời rạc.",
[("BACKGROUND","Bối cảnh"),("ANALYSIS","Phân tích"),("NEXT STEP","Điều cần làm tiếp")],"matrix",
"Một trang tốt hỗ trợ quyết định nhanh và cũng là bài test xem người viết có thật sự hiểu vấn đề không.",
["Nhồi quá nhiều text","Không có headline conclusion","Visual chỉ để trang trí"],
"Tóm một project hiện tại vào 6 ô, mỗi ô tối đa 3 bullet.",
["Có phần nào bỏ đi mà vẫn hiểu không?","Người đọc cần quyết định gì?"]),
L("8.3","Data Storytelling","Biến số liệu thành thông điệp.",
"Data Storytelling kết nối Context – Data – Meaning để trả lời câu hỏi So what?",
"Đưa baseline, change, reason, gain và implication vào cùng câu chuyện.",
"Defect giảm 0,7% sau 2 action; trend 10 ca cho thấy mức mới ổn định.",
[("CONTEXT","Bối cảnh"),("DATA","Dữ liệu then chốt"),("MEANING","Ý nghĩa/decision")],"flow",
"Nó giúp người xem không phải tự đoán ý nghĩa của biểu đồ.",
["Chỉ đưa bảng số","Quá nhiều biểu đồ","Phóng đại thay đổi nhỏ"],
"Với một chart, viết 1 headline conclusion + 1 evidence + 1 implication.",
["Người xem hiểu So what không?","Visual đang nhấn đúng điều quan trọng chưa?"]),
L("8.4","Meeting Discipline","Tổ chức họp hướng tới quyết định.",
"Họp hiệu quả có Purpose, Agenda, Decision/Output, Owner và Deadline.",
"Timebox từng agenda; gửi pre-read; kết thúc bằng action list.",
"Họp root cause 30 phút chỉ tập trung 3 giả thuyết đã có dữ liệu.",
[("TRƯỚC HỌP","Purpose + data"),("TRONG HỌP","Bám agenda"),("SAU HỌP","Action + owner")],"steps",
"Một cuộc họp 1 giờ với 8 người tiêu tốn 8 giờ nguồn lực; kỷ luật họp là kỷ luật năng suất.",
["Không rõ mục tiêu","Mời quá nhiều người","Không chốt action"],
"Trước meeting tới, ghi Purpose / Decision Needed / Pre-read / Timebox.",
["Meeting nào có thể thay bằng email?","Ai tham gia mà không có vai trò?"])]},
{"title":"9. Phát triển năng lực nghề nghiệp","subtitle":"Xây năng lực từ chuyên môn đến lãnh đạo.","lessons":[
L("9.1","T-shaped Skills","Kết hợp chiều sâu và chiều rộng.",
"T-shaped professional có một trục chuyên môn sâu và khả năng phối hợp rộng.",
"Chọn 1–2 năng lực lõi để đào sâu, đồng thời hiểu đủ về quality, project, data, people và business.",
"Process engineer sâu về lamination nhưng vẫn cần DOE, SPC, FMEA và communication.",
[("CHIỀU SÂU","Năng lực lõi"),("CHIỀU RỘNG","Khả năng phối hợp"),("IMPACT","Tạo giá trị lớn hơn")],"compare",
"T-shape giúp tránh hai cực: generalist nông và specialist bị giới hạn trong silo.",
["Học quá rộng","Chỉ giỏi kỹ thuật nhưng khó phối hợp","Không cập nhật năng lực theo tương lai"],
"Vẽ chữ T cá nhân với 2 skill sâu và 5 skill ngang.",
["Skill sâu nhất còn giá trị sau 3 năm không?","Skill ngang nào đang giới hạn ảnh hưởng?"]),
L("9.2","Deliberate Practice","Luyện tập có mục tiêu và feedback.",
"Deliberate Practice tập trung vào micro-skill khó, có feedback nhanh và tăng độ khó.",
"Chọn kỹ năng nhỏ, luyện có tiêu chí, nhận feedback và lặp lại.",
"Muốn giỏi slide, mỗi tuần viết lại một slide thật theo Pyramid Principle.",
[("MICRO-SKILL","Kỹ năng nhỏ"),("PRACTICE","Luyện có chủ đích"),("FEEDBACK","Điều chỉnh nhanh")],"steps",
"Làm việc nhiều năm không tự động tạo expertise nếu chỉ lặp lại phần đã quen.",
["Luyện thứ đã thành thạo","Mục tiêu quá rộng","Không có feedback"],
"Chọn một micro-skill và luyện 10 phút/ngày trong 2 tuần.",
["Tôi đang luyện hay chỉ lặp lại việc quen?","Feedback có đủ nhanh để sửa không?"]),
L("9.3","Learning Loop","Biến công việc thành hệ thống học tập.",
"Learning Loop biến experience thành lesson, standard và knowledge dùng lại.",
"Sau mỗi dự án: ghi lesson learned, cập nhật WI/FMEA/checklist và chia sẻ.",
"Sau customer claim, team cập nhật FMEA và thêm control vào Control Plan.",
[("EXPERIENCE","Điều đã xảy ra"),("LEARNING","Điều rút ra"),("STANDARD","Chuẩn hóa dùng lại")],"cycle",
"Nếu bài học không vào hệ thống, cùng lỗi sẽ quay lại với người khác.",
["Ghi lesson nhưng không update standard","Chỉ tìm người sai","Không chia sẻ kiến thức"],
"Tạo 1 trang Lesson Learned: Situation / Learning / Standard Updated / Audience.",
["Kiến thức nào đang nằm trong đầu một người?","Lỗi nào từng xử lý nhưng lặp lại?"]),
L("9.4","Career Portfolio","Quản lý sự nghiệp bằng bằng chứng năng lực.",
"Career Portfolio lưu lại Problem – Role – Action – Result – Learning của các case quan trọng.",
"Cập nhật hàng tháng/quý thay vì đợi tới kỳ đánh giá.",
"Thay vì nói có kinh nghiệm improvement, portfolio cho thấy 3 dự án với gain cụ thể.",
[("PROJECT","Bạn đã làm gì?"),("RESULT","Impact ra sao?"),("LEARNING","Bạn phát triển gì?")],"steps",
"Portfolio giúp tự định hướng, đánh giá năng lực và chuẩn bị cho cơ hội thăng tiến.",
["Chỉ liệt kê nhiệm vụ","Không ghi vai trò cá nhân","Không có số liệu impact"],
"Mỗi tháng thêm ít nhất 1 case theo P-R-A-R-L.",
["Nếu chỉ chọn 3 case, case nào chứng minh năng lực tốt nhất?","Portfolio cho thấy hướng phát triển gì?"])]},
{"title":"10. Hệ thống phương pháp và công cụ thực hành","subtitle":"Mô hình, checklist và công cụ áp dụng nhanh.","lessons":[
L("10.1","RACI","Làm rõ vai trò trong công việc liên phòng ban.",
"RACI phân biệt Responsible, Accountable, Consulted và Informed.",
"Mỗi deliverable nên có đúng một Accountable và số người Consulted hợp lý.",
"Trial process: PE=R, PE Manager=A, QA/PMC=C, Production=I.",
[("R","Người thực hiện"),("A","Chịu trách nhiệm cuối"),("C / I","Tham vấn / thông báo")],"matrix",
"RACI giảm delay do mơ hồ trách nhiệm và tránh tình trạng ai cũng tham gia nhưng không ai sở hữu kết quả.",
["Nhiều A cho một deliverable","R không đủ quyền","C quá nhiều làm chậm quyết định"],
"Lập RACI cho 5 deliverable lớn của một project đang chậm.",
["Ai chịu trách nhiệm cuối cùng?","Có ai nằm trong C/I chỉ vì cho chắc?"]),
L("10.2","Risk Matrix","Ưu tiên rủi ro theo xác suất và tác động.",
"Risk Matrix dùng Probability × Impact để ưu tiên risk và action.",
"Định nghĩa scale trước, chấm risk, gắn control và đánh giá residual risk.",
"Supplier change có probability medium nhưng impact customer high nên vẫn cần validation sâu.",
[("LOW","Theo dõi"),("MEDIUM","Cần action"),("HIGH","Ưu tiên cao")],"matrix",
"Ma trận tạo ngôn ngữ chung về risk, đặc biệt khi các bên có tolerance khác nhau.",
["Scale mơ hồ","Không xem residual risk","Dùng score như chân lý tuyệt đối"],
"Định nghĩa scale 1–5 bằng mô tả cụ thể và chấm 5 risk lớn nhất.",
["Hai người có chấm cùng risk giống nhau không?","Control thực sự giảm risk hay chỉ thêm giấy tờ?"]),
L("10.3","A3 Thinking","Kể câu chuyện problem solving trong một trang.",
"A3 đi theo Background – Current – Target – Analysis – Countermeasure – Follow-up.",
"Xây logic trước rồi cô đọng lên một trang; không bắt đầu bằng việc điền form.",
"Một A3 tốt giúp manager hiểu vấn đề và điểm cần quyết định trong vài phút.",
[("BACKGROUND","Bối cảnh + current"),("ANALYSIS","Root cause"),("FOLLOW-UP","Action + hiệu lực")],"flow",
"A3 là kỷ luật tư duy; nếu không thể tóm logic trên một trang, vấn đề có thể chưa đủ rõ.",
["Điền form trước khi hiểu","Countermeasure không nối root cause","Quá nhiều chữ"],
"Phác A3 bằng bút trong 20 phút cho một vấn đề thật.",
["Người ngoài dự án hiểu trong 5 phút không?","Có khoảng trống logic giữa analysis và action không?"]),
L("10.4","Personal Management System","Kết nối mục tiêu, task, calendar và review.",
"Một hệ thống cá nhân tốt đóng vai trò bộ nhớ ngoài đáng tin cậy.",
"Dùng 4 lớp: Goals – Projects/Actions – Calendar – Weekly Review.",
"Khi nhận task mới, đưa vào hệ thống, chốt deadline và next action thay vì giữ trong đầu.",
[("GOALS","Hướng đi"),("ACTIONS","Việc cần làm"),("REVIEW","Điều chỉnh định kỳ")],"cycle",
"Khi não không phải giữ mọi cam kết, bạn có nhiều năng lực hơn cho tư duy sâu và quyết định.",
["Dùng quá nhiều app","Task không có next action","Không review nên hệ thống mất tin cậy"],
"Trong 1 tuần chỉ dùng 4 nơi: Goal list / Project list / Calendar / Inbox.",
["Hệ thống giúp hay làm tôi bận hơn?","Có commitment nào chỉ tồn tại trong đầu?"])]}
]
